version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: unimart-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-unimart}
      MYSQL_USER: ${MYSQL_USER:-unimartuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-unimartpassword}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - unimart-network-dev

  # Backend Spring Boot Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: unimart-backend-dev
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/unimart
      MYSQL_USER: ${MYSQL_USER:-unimartuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-unimartpassword}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-studentunimart@gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:80
    ports:
      - "8081:8081"
    networks:
      - unimart-network-dev

  # Frontend React Application in Development Mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: unimart-frontend-dev
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8081/api
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - unimart-network-dev

networks:
  unimart-network-dev:
    driver: bridge

volumes:
  mysql-data: 