version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: unimart-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-unimart}
      MYSQL_USER: ${MYSQL_USER:-unimartuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-unimartpassword}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - unimart-network

  # Backend Spring Boot Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: unimart-backend
    container_name: unimart-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/unimart
      MYSQL_USER: ${MYSQL_USER:-unimartuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-unimartpassword}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-studentunimart@gmail.com}
      # Do not provide a default for password to enforce security
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app/src
    networks:
      - unimart-network

  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: unimart-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8081/api
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - unimart-network

networks:
  unimart-network:
    driver: bridge

volumes:
  mysql-data: 