services:
  db:
    image: mysql:latest
    container_name: unimart_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build:
      context: ../backend
    container_name: unimart_backend
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: unimart_frontend_dev
    ports:
      - "3000:3000"  # Maps port 3000 in the container to port 3000 on the host
    volumes:
      - ../frontend:/app  # Mount the frontend directory for hot reloading
      - /app/node_modules  # Preserve node_modules from container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for Windows/WSL compatibility
      - WDS_SOCKET_PORT=3000  # WebSocket port for hot reloading
    depends_on:
      - backend
    restart: always

volumes:
  db_data: 